development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: guyifeng
  pool: 5
  username: root
  password: password

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: guyifeng
  pool: 5
  username: root
  password: password
